'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option or rebuild the Visual Studio project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
Friend Class Resource

    Private Shared resourceMan As Global.System.Resources.ResourceManager

    Private Shared resourceCulture As Global.System.Globalization.CultureInfo

    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
    Friend Sub New()
        MyBase.New
    End Sub

    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Resource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property

    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = Value
        End Set
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Pivot chart.
    '''</summary>
    Friend Shared ReadOnly Property Analysis_PivotChart() As String
        Get
            Return ResourceManager.GetString("Analysis_PivotChart", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Pivot grid.
    '''</summary>
    Friend Shared ReadOnly Property Analysis_PivotGrid() As String
        Get
            Return ResourceManager.GetString("Analysis_PivotGrid", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Documentation.
    '''</summary>
    Friend Shared ReadOnly Property ControlLayout_Documentation() As String
        Get
            Return ResourceManager.GetString("ControlLayout_Documentation", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Sample.
    '''</summary>
    Friend Shared ReadOnly Property ControlLayout_Sample() As String
        Get
            Return ResourceManager.GetString("ControlLayout_Sample", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Source.
    '''</summary>
    Friend Shared ReadOnly Property ControlLayout_Source() As String
        Get
            Return ResourceManager.GetString("ControlLayout_Source", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property ControlList_Description() As String
        Get
            Return ResourceManager.GetString("ControlList_Description", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to HTTP Status Code.
    '''</summary>
    Friend Shared ReadOnly Property ControlList_HTTPStatusCode() As String
        Get
            Return ResourceManager.GetString("ControlList_HTTPStatusCode", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Reason.
    '''</summary>
    Friend Shared ReadOnly Property ControlList_Reason() As String
        Get
            Return ResourceManager.GetString("ControlList_Reason", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Response Messages.
    '''</summary>
    Friend Shared ReadOnly Property ControlList_ResponseMessages() As String
        Get
            Return ResourceManager.GetString("ControlList_ResponseMessages", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Response Schema.
    '''</summary>
    Friend Shared ReadOnly Property ControlList_ResponseSchema() As String
        Get
            Return ResourceManager.GetString("ControlList_ResponseSchema", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Features.
    '''</summary>
    Friend Shared ReadOnly Property ControlsNav_Features() As String
        Get
            Return ResourceManager.GetString("ControlsNav_Features", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to &lt;p&gt;
    '''        Because browsers and JavaScript limitations, &lt;a href=&quot;http://help.grapecity.com/componentone/NetHelp/c1mvchelpers/webframe.html#wijmo.grid.FlexGrid.Class.html&quot;&gt;FlexGird&lt;/a&gt;
    '''        control with large data(more than 50,000 rows) cannot be converted to Excel file by
    '''        &lt;a href=&quot;http://help.grapecity.com/componentone/NetHelp/c1mvchelpers/webframe.html#wijmo.grid.xlsx.FlexGridXlsxConverter.Class.html&quot;&gt;FlexGridXlsxConverter&lt;/a&gt;
    '''        or &lt;a href=&quot;http://help.grapecity.com/componentone/NetHe [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Description_Content() As String
        Get
            Return ResourceManager.GetString("Description_Content", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_Export() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_Export", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export Format:.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_ExportFormat() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_ExportFormat", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export &amp; Import.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_ExportImport() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_ExportImport", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export Name :.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_ExportName() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_ExportName", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_ExportText() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_ExportText", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Import.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_Import() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_Import", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Import.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_ImportText() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_ImportText", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to IncludeColumnHeaders:.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_IncludeColumnHeaders() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_IncludeColumnHeaders", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to OnlyCurrentPage:.
    '''</summary>
    Friend Shared ReadOnly Property FlexGridOptions_OnlyCurrentPage() As String
        Get
            Return ResourceManager.GetString("FlexGridOptions_OnlyCurrentPage", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to ~/Content/css/gcicons.css.
    '''</summary>
    Friend Shared ReadOnly Property GcIconsCssPath() As String
        Get
            Return ResourceManager.GetString("GcIconsCssPath", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property ImageExportOptions_Export() As String
        Get
            Return ResourceManager.GetString("ImageExportOptions_Export", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export Format :.
    '''</summary>
    Friend Shared ReadOnly Property ImageExportOptions_ExportFormat() As String
        Get
            Return ResourceManager.GetString("ImageExportOptions_ExportFormat", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export.
    '''</summary>
    Friend Shared ReadOnly Property ImageExportOptions_ExportText() As String
        Get
            Return ResourceManager.GetString("ImageExportOptions_ExportText", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Height :.
    '''</summary>
    Friend Shared ReadOnly Property ImageExportOptions_Height() As String
        Get
            Return ResourceManager.GetString("ImageExportOptions_Height", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Width :.
    '''</summary>
    Friend Shared ReadOnly Property ImageExportOptions_Width() As String
        Get
            Return ResourceManager.GetString("ImageExportOptions_Width", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to &lt;h4&gt;Welcome!&lt;/h4&gt;
    '''        &lt;br /&gt;
    '''        &lt;p&gt;This sample demonstrates how to control authorization in C1 DataEngine Services.&lt;/p&gt;
    '''        &lt;p&gt;Please login with pre-registered user or the register a new user.&lt;/p&gt;
    '''        &lt;p&gt;
    '''            Every user has to be assigned a role. Different roles have different permissions for accessing
    '''            the data sources and the fields.
    '''        &lt;/p&gt;.
    '''</summary>
    Friend Shared ReadOnly Property Index_Content() As String
        Get
            Return ResourceManager.GetString("Index_Content", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Email.
    '''</summary>
    Friend Shared ReadOnly Property Index_Email() As String
        Get
            Return ResourceManager.GetString("Index_Email", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Export Excel.
    '''</summary>
    Friend Shared ReadOnly Property Index_ExportExcel() As String
        Get
            Return ResourceManager.GetString("Index_ExportExcel", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Format: .
    '''</summary>
    Friend Shared ReadOnly Property Index_Format() As String
        Get
            Return ResourceManager.GetString("Index_Format", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Login.
    '''</summary>
    Friend Shared ReadOnly Property Index_Login() As String
        Get
            Return ResourceManager.GetString("Index_Login", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Register.
    '''</summary>
    Friend Shared ReadOnly Property Index_Register() As String
        Get
            Return ResourceManager.GetString("Index_Register", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Close.
    '''</summary>
    Friend Shared ReadOnly Property Layout_Close() As String
        Get
            Return ResourceManager.GetString("Layout_Close", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to ComponentOne.
    '''</summary>
    Friend Shared ReadOnly Property Layout_ComponentOne() As String
        Get
            Return ResourceManager.GetString("Layout_ComponentOne", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to http://www.grapecity.com/.
    '''</summary>
    Friend Shared ReadOnly Property Layout_GrapeCityUrl() As String
        Get
            Return ResourceManager.GetString("Layout_GrapeCityUrl", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to GrapeCity, Inc. All Rights Reserved..
    '''</summary>
    Friend Shared ReadOnly Property Layout_License1() As String
        Get
            Return ResourceManager.GetString("Layout_License1", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
    '''</summary>
    Friend Shared ReadOnly Property Layout_License2() As String
        Get
            Return ResourceManager.GetString("Layout_License2", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Loading....
    '''</summary>
    Friend Shared ReadOnly Property Layout_Loading() As String
        Get
            Return ResourceManager.GetString("Layout_Loading", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to ASP.NET Web API Explorer.
    '''</summary>
    Friend Shared ReadOnly Property Layout_LongTitle() As String
        Get
            Return ResourceManager.GetString("Layout_LongTitle", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to https://www.grapecity.com/en/webapi/.
    '''</summary>
    Friend Shared ReadOnly Property Layout_ProductUrl() As String
        Get
            Return ResourceManager.GetString("Layout_ProductUrl", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Web API Explorer.
    '''</summary>
    Friend Shared ReadOnly Property Layout_ShortTitle() As String
        Get
            Return ResourceManager.GetString("Layout_ShortTitle", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Have you seen this? C1Studio Web API.
    '''</summary>
    Friend Shared ReadOnly Property Layout_TwitterText() As String
        Get
            Return ResourceManager.GetString("Layout_TwitterText", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to About.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_About() As String
        Get
            Return ResourceManager.GetString("SiteNav_About", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to https://www.grapecity.com/en/webapi/.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_AboutUrl() As String
        Get
            Return ResourceManager.GetString("SiteNav_AboutUrl", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to FREE TRIAL.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_FreeTrial() As String
        Get
            Return ResourceManager.GetString("SiteNav_FreeTrial", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to https://www.grapecity.com/en/download/componentone-studio.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_FreeTrialUrl() As String
        Get
            Return ResourceManager.GetString("SiteNav_FreeTrialUrl", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Pricing.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_Pricing() As String
        Get
            Return ResourceManager.GetString("SiteNav_Pricing", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to https://www.grapecity.com/en/pricing.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_PricingUrl() As String
        Get
            Return ResourceManager.GetString("SiteNav_PricingUrl", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Sign out.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_SignOut() As String
        Get
            Return ResourceManager.GetString("SiteNav_SignOut", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Support.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_Support() As String
        Get
            Return ResourceManager.GetString("SiteNav_Support", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to http://supportone.componentone.com/login.
    '''</summary>
    Friend Shared ReadOnly Property SiteNav_SupportUrl() As String
        Get
            Return ResourceManager.GetString("SiteNav_SupportUrl", resourceCulture)
        End Get
    End Property
End Class
